### PR TITLE
Use the concurrent golang cluster loader implementation

### PR DESCRIPTION
**Pull request by akrzos**

### CODE REVIEW

**Comment by akrzos** [comment]
DNM - Do not merge yet.

We need some object waits at the end to correctly determine when the workload "completes"

**Comment by akrzos** [comment]
FYI @chaitanyaenr

**Comment by akrzos** [comment]
Once this lands (https://github.com/openshift/origin/pull/23550) we should have mastervertical using concurrent cluster loader in which the objects are waited for.

**Review by jmencak — APPROVED** [review]
Untested, but in line with recent cluster-loader changes.

**Pull request merged**
