### PR TITLE
Remove privileged requirement from HostNetwork tests

### PR DESCRIPTION
**Pull request by akrzos**
Remove privileged requirement from HostNetwork tests and instead require "AUDIT_WRITE" capability.

### CODE REVIEW

**Comment by akrzos** [comment]
@jmencak @chaitanyaenr @sjug @Deepthidharwar PTAL but DNM (Do Not Merge) yet as I am still testing.

**Comment by jmencak** [comment]
I'm all for least-privileged if this really works.

**Comment by akrzos** [comment]
It is ready PTAL and merge.

**Comment by akrzos** [comment]
Just rebased off recent changes.

**Comment by jmencak** [comment]
LGTM, successfully tested with [scale-ci-deploy](https://github.com/openshift-scale/scale-ci-deploy) without any issues.

**Pull request merged**
