### PR TITLE
Add Scaling workload

### PR DESCRIPTION
**Pull request by akrzos**

### CODE REVIEW

**Comment by akrzos** [comment]
DNM yet, Thanks

**Comment by akrzos** [comment]
Ok This is ready.  It includes a var for pass/fail criteria (EXPECTED_SCALE_DURATION) . I would like to use this model in conjunction with the scraper and comparison tooling for all future pass/fail test criteria.

**Comment by akrzos** [comment]
@jmencak @chaitanyaenr PTAL

**Review by chaitanyaenr — APPROVED** [review]
LGTM, worked fine on a test cluster. We need to make sure is that if we provision a cluster with 3 workers to start we might have to plan for that logic like 3 azs instead of 4 like @akrzos mentioned.

**Pull request merged**
