### PR TITLE
source the pbench-agent/profile

### PR DESCRIPTION
**Pull request by mohit-sheth**
we ship the results to pbench server even when pbench-agents are not enabled.

### CODE REVIEW

**Review by aakarshg — APPROVED** [review]
not sure if this is a feature, but either way the implications of setting the vars to true vs false does need to be documented well on.

**Comment by chaitanyaenr** [comment]
@aakarshg agreed, maybe we can make the docs ( https://github.com/openshift-scale/workloads/blob/master/docs/nodevertical.md#pbench_instrumentation ) more explicit by adding a note that pbench can be used without enabling agents and the results can be shipped to the server.

**Comment by mohit-sheth** [comment]
@chaitanyaenr ^ Done

**Review by chaitanyaenr — APPROVED** [review]
LGTM

**Pull request merged**
