### PR TITLE
Add support to run workloads on Azure

### PR DESCRIPTION
**Pull request by chaitanyaenr**
This commit sets the azure authentication needed to run workloads
on OCP running on top of Azure.

### CODE REVIEW

**Comment by aakarshg** [comment]
I think it'd make sense to add the azure specific tasks to a separate role, and then call the role in each of playbook. This would also help with code  maintainability

**Comment by chaitanyaenr** [comment]
@aakarshg nice suggestion, updated the PR. PTAL.

**Review by aakarshg — COMMENTED** [review]
LGTM, but will recommend another reviewer to sign off + merge.

**Comment by chaitanyaenr** [comment]
@wabouhamad @jtaleric @mohit-sheth need one more set of eyes when you get time please.

**Review by jtaleric — APPROVED** [review]
LGTM

**Comment by chaitanyaenr** [comment]
Thanks for the review @aakarshg @jtaleric.

**Pull request merged**
